#!/bin/sh

git filter-branch --env-filter '

OLD_EMAIL="aldahir@Aldahirs-Macbook-Pro.local"
CORRECT_NAME="Jose Aldahir Moreno"
CORRECT_EMAIL="jamoren1@uci.edu"

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags